# Generated by Django 2.0 on 2018-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(to='bookclubapp.Books'),
        ),
    ]
