# Generated by Django 2.0 on 2018-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapp', '0002_auto_20180530_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_posted']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_posted']},
        ),
        migrations.RemoveField(
            model_name='groups',
            name='books',
        ),
        migrations.AddField(
            model_name='groups',
            name='books',
            field=models.ManyToManyField(to='bookclubapp.Books'),
        ),
    ]
