# Generated by Django 2.0 on 2018-05-31 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookclubapp', '0004_auto_20180530_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='Group_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclubapp.Review'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='books',
            field=models.ManyToManyField(null=True, to='bookclubapp.Books'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(null=True, to='bookclubapp.Profile'),
        ),
    ]
