# Generated by Django 2.0 on 2018-05-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapp', '0005_auto_20180531_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclubapp.Review'),
        ),
    ]
